# Generated by Django 4.2.1 on 2023-06-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_templatetable_alter_allusers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='first_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='last_name',
            field=models.CharField(max_length=250),
        ),
    ]
