# Generated by Django 4.2.1 on 2023-06-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_allusers_first_name_alter_allusers_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
