# Generated by Django 4.2.1 on 2023-06-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_allusers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
