# Generated by Django 4.2.1 on 2023-06-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_interests_userinterests'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interests',
            table='All Interests',
        ),
        migrations.AlterModelTable(
            name='userinterests',
            table='User Interests',
        ),
    ]
