# Generated by Django 4.2.2 on 2023-07-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardcount",
            name="totalUserInterest",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dashboardcount",
            name="totalUsers",
            field=models.IntegerField(default=0),
        ),
    ]
