# Generated by Django 4.2.2 on 2023-07-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_dashboardcount_totaluserinterest_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dashboardcount",
            old_name="totalUsers",
            new_name="count",
        ),
        migrations.RemoveField(
            model_name="dashboardcount",
            name="totalUserInterest",
        ),
        migrations.AddField(
            model_name="dashboardcount",
            name="name",
            field=models.CharField(default="name", max_length=250),
        ),
    ]
